import type { LooseRequired } from '@vue/shared';
import { pick } from 'lodash-es';
import type { Events, ExtractPropTypes, PropType } from 'vue';

function ont<T>() {
	return {
		type: Function as PropType<(payload: T) => void>,
	} as const;
}
export const propsEvents = {
	onCopy: ont<ClipboardEvent>(),
	onCut: ont<ClipboardEvent>(),
	onPaste: ont<ClipboardEvent>(),
	onCompositionend: ont<CompositionEvent>(),
	onCompositionstart: ont<CompositionEvent>(),
	onCompositionupdate: ont<CompositionEvent>(),
	onDrag: ont<DragEvent>(),
	onDragend: ont<DragEvent>(),
	onDragenter: ont<DragEvent>(),
	onDragexit: ont<DragEvent>(),
	onDragleave: ont<DragEvent>(),
	onDragover: ont<DragEvent>(),
	onDragstart: ont<DragEvent>(),
	onDrop: ont<DragEvent>(),
	onFocus: ont<FocusEvent>(),
	onFocusin: ont<FocusEvent>(),
	onFocusout: ont<FocusEvent>(),
	onBlur: ont<FocusEvent>(),
	onChange: ont<Event>(),
	onBeforeinput: ont<InputEvent>(),
	onFormdata: ont<FormDataEvent>(),
	onInput: ont<InputEvent>(),
	onReset: ont<Event>(),
	onSubmit: ont<SubmitEvent>(),
	onInvalid: ont<Event>(),
	onFullscreenchange: ont<Event>(),
	onFullscreenerror: ont<Event>(),
	onLoad: ont<Event>(),
	onError: ont<Event>(),
	onKeydown: ont<KeyboardEvent>(),
	onKeypress: ont<KeyboardEvent>(),
	onKeyup: ont<KeyboardEvent>(),
	onDblclick: ont<MouseEvent>(),
	onMousedown: ont<MouseEvent>(),
	onMouseenter: ont<MouseEvent>(),
	onMouseleave: ont<MouseEvent>(),
	onMousemove: ont<MouseEvent>(),
	onMouseout: ont<MouseEvent>(),
	onMouseover: ont<MouseEvent>(),
	onMouseup: ont<MouseEvent>(),
	onAbort: ont<UIEvent>(),
	onCanplay: ont<Event>(),
	onCanplaythrough: ont<Event>(),
	onDurationchange: ont<Event>(),
	onEmptied: ont<Event>(),
	onEncrypted: ont<MediaEncryptedEvent>(),
	onEnded: ont<Event>(),
	onLoadeddata: ont<Event>(),
	onLoadedmetadata: ont<Event>(),
	onLoadstart: ont<Event>(),
	onPause: ont<Event>(),
	onPlay: ont<Event>(),
	onPlaying: ont<Event>(),
	onProgress: ont<ProgressEvent>(),
	onRatechange: ont<Event>(),
	onSeeked: ont<Event>(),
	onSeeking: ont<Event>(),
	onStalled: ont<Event>(),
	onSuspend: ont<Event>(),
	onTimeupdate: ont<Event>(),
	onVolumechange: ont<Event>(),
	onWaiting: ont<Event>(),
	onSelect: ont<Event>(),
	onScroll: ont<Event>(),
	onScrollend: ont<Event>(),
	onTouchcancel: ont<TouchEvent>(),
	onTouchend: ont<TouchEvent>(),
	onTouchmove: ont<TouchEvent>(),
	onTouchstart: ont<TouchEvent>(),
	onAuxclick: ont<PointerEvent>(),
	onClick: ont<PointerEvent>(),
	onContextmenu: ont<PointerEvent>(),
	onGotpointercapture: ont<PointerEvent>(),
	onLostpointercapture: ont<PointerEvent>(),
	onPointerdown: ont<PointerEvent>(),
	onPointermove: ont<PointerEvent>(),
	onPointerup: ont<PointerEvent>(),
	onPointercancel: ont<PointerEvent>(),
	onPointerenter: ont<PointerEvent>(),
	onPointerleave: ont<PointerEvent>(),
	onPointerover: ont<PointerEvent>(),
	onPointerout: ont<PointerEvent>(),
	onBeforetoggle: ont<ToggleEvent>(),
	onToggle: ont<ToggleEvent>(),
	onWheel: ont<WheelEvent>(),
	onAnimationcancel: ont<AnimationEvent>(),
	onAnimationstart: ont<AnimationEvent>(),
	onAnimationend: ont<AnimationEvent>(),
	onAnimationiteration: ont<AnimationEvent>(),
	onSecuritypolicyviolation: ont<SecurityPolicyViolationEvent>(),
	onTransitioncancel: ont<TransitionEvent>(),
	onTransitionend: ont<TransitionEvent>(),
	onTransitionrun: ont<TransitionEvent>(),
	onTransitionstart: ont<TransitionEvent>(),
} as const;
const events = Object.keys(propsEvents) as unknown as keyof typeof propsEvents;
export function extractAttributesFromProps<
	T extends LooseRequired<Readonly<ExtractPropTypes<typeof propsEvents>> & Readonly<{}> & {}>,
>(props: T): Pick<T, keyof Events> {
	return pick(props, events);
}
