// prettier-ignore
const news = [{id: "news1", text: "不会做增量游戏怎么办？看风灵作成的原代码一个半小时就学会了！"},
{id: "news2", text: "这个游戏实际上的名称是RBNR^5，因为已经重制过4次了。"},
{id: "news3", text: "尝试用ai做了一个增量游戏，结果bug比功能多"},
{id: "news4", text: "请选择你期望的实验人员。 [A]砂糖   [B]大黑塔  [C]阮·梅"},
{id: "news4.1", text: "请选择你期望的实验对象。 [A]你自己   [B]你自己   [C]你自己   [D]你自己~~~~~~"},
{id: "news5", text: "<img src='baixie.png' /><img src='baixie.png' /><img src='baixie.png' />"},
{id: "news6", text: "googology意思是“大数学”，音译为“果糕逻辑”，使用果糕逻辑这个音译名以表示内容之不严谨。"},
{id: "news7", text: "滚动新闻的添加速度将是毁灭性的！！！！！！"},
{id: "news8", text: "代码组建议了一个事项，因为这样他们就只需要复制粘贴了("},
{id: "news9", text: "当3个人同时写代码，Bug和Conflict都将是毁灭性的……"},
{id: "news10", text: "RBNR初期以平均5小时一次大更新的节奏稳步推进着。"},
{id: "news11", text: "@艾斯亿诶嗯叉了叉"},
{id: "news12", text: "要是ADE有我们这个开发速度已经到被粉碎的现实了。"},
{id: "news13", text: "完成第-1层（成就）的时间等于通关这个游戏的时间，完成第-2层（新闻）的时间取决于写新闻代码的人添加了多少奇怪的条件"},
{id: "news14", text: "unicode命名法：String.fromCharCode(初始名字.charCodeAt() + n)，只有风灵作成重置层取名参考这玩意儿"},
{id: "news15", text: "Breaking News! 等待10秒，用代码实现Fake news!"},
{id: "news16", text: "AD16 mod 2 = 1"},
{id: "news17", text: "你知道吗？Bourgain证明了Δ(x)=O(x^517/1648+ε)结果被发现是错的，下次你做错数学题的时候想想他吧"},
{id: "news18", text: "@帝诶了艾斯帝诶了"},
{id: "news19", text: "有一颗很大的树，它指引了人们的道路，但是一开始种这棵树的时候，有一年时间没管它，树塌了，尝试重新种这棵树，当它制取荫凉的时候，树炸了"},
{id: "news20", text: "Cookie Clicker NG++ 竟然有C2S的内容即《中生代山谷增加糖块加成，超越增加牛奶加成》"},
{id: "news21", text: "扭敧是有意义的词。时间扭敧：使游戏时间非线性增长，主要作用是显著降低时间墙。"},
{id: "news22", text: "nanenan /'nænenən/ n.无大数js的放置/增量游戏的终局 v.玩增量游戏出现异常"},
{id: "news23", text: "反物质天神，是饼干点击邪恶的老奶奶，是协同放置的最后一个饼干升级"},
{id: "news24", text: "24岁，事学生，是一个一个一个"},
{id: "news25", text: "大冲突（Big Conflict）和大发散（Big Divergent）的下一场灾难是什么？"},
{id: "news26", text: "hard_shuati降临RBNR引发大侵袭"},
{id: "news27", text: "滚动新闻是可以被关闭的"},
{id: "news28", text: "在模糊模式下游玩游戏可以获得惊喜"},
{id: "news29", text: "游戏崩坏始于hard_shuati，警惕每一个蒋小绒！"},
{id: "news30", text: "我要吃██的大胸，小胸，翅尖，翅中，翅根，大腿，头，冠，爪，脖子，锁骨，皮，胗和心脏。喂！这里不是食堂！"},
{id: "news31", text: "Hyp Cos是本游戏的最后一个层级"},
{id: "news32", text: "本游戏曾经在乘法层级的末期有一个三重指数级别的发散，如果你看到了这条新闻，就说明这个发散已被移除了。"},
{id: "news33", text: "谁能把这坨东西填满"},
{id: "news34", text: "你现在看到的挑战4是一场血腥战争的最终结果"},
{id: "news35", text: "The first one is always <i>free</i> fake."},
{id: "news36", text: "不懂就问，这是病毒树吗，你再加多点升级都能堆到一天了"},
{id: "news37", text: "在设计初期质因数几乎一点用都没有，后来改了，但造成了发散"},
{id: "news38", text: "游玩对数运算有助于提高天文学家EdenGameMaster的寿命"},
{id: "news39", text: "这是放置游戏，这是劝退树，更是革命空闲"},
{id: "news40", text: "Oni gaming在时间墙大赛中获得了第二名，第一名是RBNR"},
{id: "news40.1", text: "Omi gaming在逼氪大赛中获得了第一名"},
{id: "news41", text: "后继层级曾经延伸到了2<sup>1024</sup>这么大的数字"},
{id: "news42", text: "黑塔女士举世无双！黑塔女士聪明绝顶！黑塔女士沉鱼落雁！钥落千星，才震银宇，难描绝美，短言难述…解弧波算法之真谛，造模拟宇宙为真知，虚构难藏实之魅力，真伪何妨追随与否，此刻……黑门永存！"},
{id: "news42.1",text:"大黑举世无双！大黑聪明绝顶！大黑沉鱼落雁！钥落Q群，才震群友，难描作品，短言难述…解增量游戏之真谛，造PEIT为真知，禁言难藏增量魅力，模组何妨树状与否，此刻……大黑永存！"},
{id: "news43", text: "<b>大机罢</b>"},
{id: "news44", text: "如果你只挂了1个加法能量，那你简直是fvv，如果你挂了6个加法能量，那么你是速通或者正常人，如果你挂了31个加法能量，那么你很有实力，如果你挂了156个加法能量，说明你把这个网页给弄忘了"},
{id: "news45", text: "oiiaiioiiaii __猫__ oiiaiioiiaii __猫__ oiiaiioiiaii __猫__ oiiaiioiiaii __猫__ "},
{id: "news46", text: "不幸的是我们用完了滚动新闻的梗，只能让你看这段话了"},
{id: "news47", text: "新闻对我来说是增量游戏聚集地(在梗文字中发现了少量增量游戏)"},
{id: "news48", text: "两个人同时修复一个bug导致bug又回来了，要三个人同时修复才能修好这个bug，ω个人同时修复一个bug导致bug又回来了，要ω+1个人同时修复才能修好这个bug"},
{id: "news49", text: "求树的高度的方法：三角函数，深度优先搜索，googology"},
{id: "news50", text: "亲爱的玩家，当你秒赤RBNR的时候，要记得是天文学家EdenGameMaster帮你削弱了巨额的时间墙。如若没有EdenGameMaster的努力，你达到指数层至少需要<del>1.79e308</del>1无限（已达一重大脆）秒抵达指数层"},
{id: "news51", text: "既然IMR有软上限，溢出，淤积，为什么RBNR不出现这些机制？"},
{id: "news52", text: "前面忘了 中间忘了 后面也忘了 这项目干啥来着"},
{id: "news53", text: "史上平衡最差的增量游戏是什么？IMR IDR WSC MDVI算什么，RBNR才是真神"},
{id: "news54", text: "Vorona言：antiest-booster gainest"},
{id: "news55", text: "这个人不在人员名单上，但他有自爆果汁，所以他是科学家人员"},
{id: "news56", text: "请问这个黄豆双手向下跪地是什么意思？"},
{id: "news57", text: "[暂不支持该消息类型，请用 [暂不支持该消息类型，请用 ...... 查看] 查看]"},
{id: "news58", text: "这公司不实在，买的软盘正面写着3M，背面写的却是1.44M，格式化完只有1.38M"},
{id: "news59", text: "本次你连续1.1981F7次掷十面骰出现1，你看到这句话的概率是1/1.1981F8，也就是1/1.1981F8%"},
{id: "news60", text: "本游戏的终局不是在加强疫苗中到达1.1981F7数值"},
{id: "news61", text: "你还记得看到的上一条新闻是什么吗"},
{id: "news62", text: "我们的留言板上写着指数层级早已前瞻完成，但你猜真的完成了吗"},
{id: "news63", text: "什么？你问我们没事干的时候干什么？我们RBNR制作组没有没事干的时候"},
{id: "news64", text: "发散是反时间墙，时间墙是反发散，既不发散又不时间墙是正常的，既发散又时间墙是增量游戏作者故意设计的"},
] as const as {
	id: string;
	text: string;
	unlocked?: boolean;
	dynamic?: boolean;
	reset?: () => void;
	onClick?: () => string | undefined;
}[];
export default news;
