// prettier-ignore
export default [{id: "news1", text: "不会做增量游戏怎么办？看风灵作成的原代码一个半小时就学会了！"},
{id: "news2", text: "这个游戏实际上的名称是RBNR^5，因为已经重制过4次了。"},
{id: "news3", text: "尝试用ai做了一个增量游戏，结果bug比功能多"},
{id: "news4", text: "请选择你期望的实验人员。 [A]砂糖   [B]大黑塔  [C]阮·梅"},
{id: "news4.1", text: "请选择你期望的实验对象。 [A]你自己   [B]你自己   [C]你自己   [D]你自己~~~~~~"},
{id: "news5", text: "<img src='baixie.png' /><img src='baixie.png' /><img src='baixie.png' />"},
{id: "news6", text: "googology意思是“大数学”，音译为“果糕逻辑”，使用果糕逻辑这个音译名以表示内容之不严谨。"},
{id: "news7", text: "滚动新闻的添加速度将是毁灭性的！！！！！！"},
{id: "news8", text: "代码组建议了一个事项，因为这样他们就只需要复制粘贴了("},
{id: "news9", text: "当3个人同时写代码，Bug和Conflict都将是毁灭性的……"},
{id: "news10", text: "RBNR初期以平均5小时一次大更新的节奏稳步推进着。"},
{id: "news11", text: "@艾斯亿诶嗯叉了叉"},
{id: "news12", text: "要是ADE有我们这个开发速度已经到被粉碎的现实了。"},
{id: "news13", text: "完成第-1层（成就）的时间等于通关这个游戏的时间，完成第-2层（新闻）的时间取决于写新闻代码的人添加了多少奇怪的条件"},
{id: "news14", text: "unicode命名法：String.fromCharCode(初始名字.charCodeAt() + n)，很多游戏重置层取名都参考这玩意儿"},
{id: "news15", text: "Breaking News! 等待10秒，用代码实现Fake news!"},
{id: "news16", text: "AD16 mod 2 = 1"},
{id: "news17", text: "你知道吗？Bourgain证明了Δ(x)=O(x^517/1648+ε)结果被发现是错的，下次你做错数学题的时候想想他吧"},
{id: "news18", text: "@帝诶了艾斯帝诶了"},
{id: "news19", text: "有一颗很大的树，它指引了人们的道路，但是一开始种这棵树的时候，有一年时间没管它，树塌了，尝试重新种这棵树，当它制取荫凉的时候，树炸了"},
{id: "news20", text: "Cookie Clicker NG++ 竟然有C2S的内容即《中生代山谷增加糖块加成，超越增加牛奶加成》"},
{id: "news21", text: "扭敧是有意义的词。时间扭敧：使游戏时间非线性增长，主要作用是显著降低时间墙。"},
{id: "news22", text: "nanenan /'nænenən/ n.无大数js的放置/增量游戏的终局 v.玩增量游戏出现异常"},
{id: "news23", text: "反物质天神，是饼干点击邪恶的老奶奶，是协同放置的最后一个饼干升级"},
{id: "news24", text: "24岁，事学生，是一个一个一个"},
{id: "news25", text: "大冲突（Big Conflict）和大发散（Big Divergent）的下一场灾难是什么？"},
{id: "news26", text: "hard_shuati降临RBNR引发大侵袭"},
{id: "news27", text: "滚动新闻是可以被关闭的"},
{id: "news28", text: "在模糊模式下游玩游戏可以获得惊喜"},
{id: "news29", text: "游戏崩坏始于hard_shuati，警惕每一个蒋小绒！"},
{id: "news30", text: "我要吃██的心脏"},
{id: "news31", text: "Hyp Cos是本游戏的最后一个层级"},
{id: "news32", text: "本游戏曾经在乘法层级的末期有一个双重指数级别的发散，如果你看到了这条新闻，就说明这个发散已被移除了。"},
{id: "news33", text: "谁能把这坨东西填满"},
{id: "news34", text: "你现在看到的挑战4是一场血腥战争的最终结果"},
{id: "news35", text: "The first one is always free."},
{id: "news36", text: "不懂就问，这是病毒树吗，你再加多点升级都能堆到一天了"},
{id: "news37", text: "在设计初期质因数几乎一点用都没有，后来改了，但造成了发散"},
{id: "news38", text: "游玩对数运算有助于提高天文学家的寿命"},
{id: "news39", text: "这是放置游戏，这是劝退树，更是革命空闲"},
{id: "news40", text: "Omi gaming在时间墙大赛中获得了第二名"},
{id: "news41", text: "后继层级曾经延伸到了2^1024这么大的数字"},
{id: "news42", text: "黑塔女士举世无双！黑塔女士聪明绝顶！黑塔女士沉鱼落雁！钥落千星，才震银宇，难描绝美，短言难述…解弧波算法之真谛，造模拟宇宙为真知，虚构难藏实之魅力，真伪何妨追随与否，此刻……黑门永存！"},
] as {
	id: string;
	text: string;
	unlocked?: boolean;
	dynamic?: boolean;
	reset?: () => void;
	onClick?: () => string | undefined;
}[];
