import type { $t } from '@/utils/types';
import { deepCopy, player } from './save';
import { getMessage, i18n } from '@/utils/i18n';
import { temp } from './temp-data';

const plotcontents = {
	'zh-CN': [
		[
			'大基数在支撑集合论宇宙的序数高塔中飘荡。',
			'随后，Numerorum在“大数世界”的边疆醒来。',
			'Numerorum\t……',
			'Numerorum\t终于……醒来了。',
			'Numerorum看看这熟悉又陌生的世界。',
			'Numerorum\t世界改变了许多。',
			'Numerorum\t但我的使命还没有完成……',
			'远处的序数高塔若隐若现。',
			'Numerorum\t该从哪里开始我的目标呢？',
			'Numerorum\t负数显然离我的目标有点远。',
			'Numerorum\t就先从0开始吧。',
		],
		[
			'随着第一次后继运算的进行，Numerorum感受到了曾经的气息。',
			'Numerorum\t这熟悉的感觉。',
			'Numerorum\t这一个个连成串的数字，可能是我这一段旅程中唯一的伙伴了。',
			'Numerorum\t虽然长路漫长，但是好的开始是成功的一半。',
			'Numerorum\t加油。',
			'敢问路在何方？路在脚下。',
		],
		[
			'Numerorum\t这个能量，有一种让人舒服的感觉。',
			'Numerorum\t花费这么多数字是值得的。',
			'Numerorum\t我怎么感觉到谁在看着我？',
			'Numerorum望向半空中的序数高塔。',
			'高塔高耸入云，无法看穿。',
			'Numerorum\t注视感来自高塔的顶端。',
			'能登上高塔之巅的人，Numerorum暂时还无法窥探。',
			'Numerorum\t究竟是谁建造了这么高的建筑？',
			'Numerorum\t可惜我现在还很弱小，无法攀登这座高塔。',
			'Numerorum\t那就立下小目标，先进入序数的层次。',
		],
		[
			'Numerorum\t这是一种更精密的能量。',
			'Numerorum\t我选择的路没有错误。',
			'Numerorum\t但是那种来自序数之塔的注视感更加强烈了。',
		],
		['Numerorum\t呼……该做一些有挑战性的事情了。', 'Numerorum\t我希望能从中吸取一些经验。'],
		[
			'Numerorum\t我感觉到了……我已经接近了。',
			'Numerorum\t再努把力。登上高塔，恐怕我就要引来一些对手了。',
			'来自高塔的注视仍然没有消除，而且随着Numerorum接近高塔而越来越强。',
			'???\tHydra\t……',
			'Numerorum\t什么？',
			'神秘的声音一闪而逝。',
			'Numerorum\t不好，我好像被盯上了。',
		],
		[
			'Numerorum来到了天文学家的店铺，它坐落在高塔旁的悬崖边。',
			'Numerorum\t你就是天文学家？我现在需要一些你们的帮助。',
			'天文学家\t你好，我是天文学家的头领，你需要我们来帮你计算吗？',
			'Numerorum\t是的，我现在需要这些数据。',
		],
		[
			'Numerorum\t这些东西我也研究得差不多了，是时候出发了。',
			'Numerorum\t越接近序数之塔，感觉这里的压制就越强。',
			'Numerorum\t我又有了新的感悟……',
		],
		[
			'Numerorum\t果然，就是这样。',
			'Numerorum\t这个东西散发的能量足以打破高塔周围的屏障了。',
			'Numerorum\t不过，我可能需要付出一些代价来激活它。',
		],
		[
			'Numerorum\t到达ω了吗。',
			'Numerorum\t这里，就是序数之塔的内部？',
			'Numerorum\t之前的后继，加法，乘法，指数都被献祭掉了，不过我可以在这个领域继续。',
		],
		[
			'Numerorum\t这里就是……等等!',
			'旁白\t一个声音突然充斥了高塔的这一层。',
			'???\tHydra\t你竟然能到达这里，真是让我刮目相看。',
			'Numerorum\t你在哪？出来！',
			'???\tHydra\t呵呵呵，你还没有资格见到我。',
			'Numerorum\t……',
			'???\tHydra\t不必惊讶，虽然你可能永远也见不到我罢了。',
			'Numerorum\t可恶，不要瞧不起人！就算你在高塔的顶端，我也迟早见到你！',
			'不管Numerorum怎么说，神秘的声音都不再回应。',
		],
		[
			'Numerorum\t不好，前面被堵住了。',
			'Numerorum\t这是什么东西，为什么我碰一下就会感觉头晕……',
			'旁白\tNumerorum感觉自己浑身力气都被抽走了。',
			'Numerorum\t不好，被暗算了！我的能量都被这东西抽走了，不行，我得想办法过去。',
		],
		[
			'Numerorum\t好了，我算是摸透了这玩意的机制了......这东西没有任何陷阱，我可以不断从中获取力量。',
			'Numerorum\t不用再假装害怕这朊病毒了。',
		],
		[
			'Numerorum\t这种能量比我所见到的东西都要强大。',
			'非递归能量蕴含的强大气息在高塔的这一层中回荡。',
			'Numerorum\t我感觉到它还有很多潜力可以挖掘……',
			'Numerorum\t或许可以试试研究一下它。',
			'Numerorum尝试了几种方式来改造非递归能量，最后它成为了非递归定理。',
			'Numerorum\t这个东西看起来很有用。不过它来之不易，要小心谨慎地安排它。',
			'忽然，Numerorum在前方看到了熟悉的身影。',
			'Numerorum\t是你！你竟然登上了高塔。',
			'天文学家\t呵呵，我作为天文学家，自然要站在高处了。',
			'天文学家\t你可能不知道非递归定理的妙用。',
			'天文学家\t我这里有一些困难的挑战……也许会对你有帮助。',
			'天文学家向Numerorum讲述了一些挑战。',
			'天文学家\t你可以向我问一些问题。我在高塔上待过很长时间，对这里比较熟悉。',
			'Numerorum\t这座高塔有多高呢？',
			'天文学家\t很高，以你现在的能力根本无法登顶。',
			'天文学家\t而且在高塔上还有两个暴君，他们会千方百计地阻止别人变强。',
			'Numerorum不禁想到了之前的神秘声音。',
			'天文学家\t另外，要记住这件事：当你凝视星空的时候，星空也在凝视你。',
			'Numerorum\t你是说……天空是有意识的？',
			'天文学家\t是的，我们天文学家百分百确定这件事，整个天空都是同一个生命。',
			'Numerorum\t（如果这样，我的使命或许可以……）',
			'天文学家\t差不多就这样了吧，你继续向前吧。这座高塔上有很多攀登者，有些还在试图突破暴君们的阻拦。',
			'天文学家\t比如说一个叫VeryRDefie的人，爬着爬着被\\(\\log_{\\alpha}(0)\\)感染了ω病毒，快要死了。',
		],
		[
			'Numerorum通过了1次挑战',
			'天文学家\t看来你离高塔的顶端更近了一步。',
			'天文学家离开了。',
			'Numerorum\t看来在这里，朊病毒不仅不会给我帮助，反而会置我于死地。',
			'旁边爬上来了一个人，看起来很紧张。',
			'Numerorum\t你是谁？',
			'???\tVeryRDefie\t我叫VeryRDefie。',
			'Numerorum\t嗯？你就是刚刚天文学家说的那个……',
			'VeryRDefie\t对，要不是我机智，就死在那个可恶的陷阱里面了。',
			'VeryRDefie\t你叫什么名字？',
			'Numerorum\t我叫Numerorum，这陷阱到底是个什么情况？',
			'VeryRDefie\t高塔里这个部位被九头蛇布置了一大堆这样的东西，有些是\\(\\frac{1}{0}\\)，有些是\\(\\ln(-x)\\)，你要小心。',
			'VeryRDefie\t尤其是ω病毒，非常恐怖。如果遇到了，基本上就是必死的局面。',
			'Numerorum\t我看到墙上写了一些字……这些是不是……',
			'墙上写着一行字，依稀能辨认出是一个攀登者在这里遭遇了不幸。',
			'VeryRDefie观察了一下，若有所思。',
			'VeryRDefie\t这个是那个人所拥有的九头蛇能量突然变成了负数。这种也基本上没救了。',
			'VeryRDefie\t之前非递归挑战1和序数前的指数就出现了ω病毒。',
			'Numerorum\t啊？这么危险？！而且居然扩散到了序数之塔外。',
			'VeryRDefie\t我和几个同伴已经把它们清理得差不多了，不过还是要小心。',
			'VeryRDefie\t另外，朊病毒在挑战中不可能帮助你，这些挑战都需要你自力更生。',
			'VeryRDefie\t 但是，在你靠自己的能力突破挑战后，你也会拥有更强大的研究。',
			'VeryRDefie展示了新的非递归研究。',
			'Numerorum\t这些东西我觉得很不错。',
			'Numerorum\t对了，你说你的同伴……是谁？',
			'VeryRDefie\t他们在别的地方。你应该都能遇到。',
		],
		[
			'Numerorum\t爽，这UNOCF和里程碑就是爽!',
			'???\tHydra\t不要太爽了，你还没过Small Hydra Ordinal。',
			'Numerorum\t...时间总有一天会击败你的',
			'???\tHydra\t实践(时间)是谁？',
		],
		[
			'Numerorum\tUNOCF也太强了，但是我还没到达(0)(1³)(2³)(3³)...',
			'VeryRDefie\t其实可以这样……',
			'VeryRDefie展示了新的强大非递归研究(coming s∞n)。',
			'Numerorum\t唉，确实。',
			'???\tHydra\t...',
			'VeryRDefie\t嗯？那个神秘的声音又出现了，他很令人<$bx>，散播ω病毒的就是他。',
			'???\tHydra\t你们两个会遭到',
		],
		[
			'Numerorum\t这个(Bashicu)矩阵系统基本上就是这样了。还有什么？',
			'旁白\tNumerorum脑中灵光一闪。',
			'Numerorum\t或许我可以以这个的启发去寻找更强力的记号。我或许可以试试用我所有的解数来创造出这样的东西。', // 你会遭到报应的
		],
		[
			'Numerorum\t冷静。',
			'Numerorum\t这里似乎是非递归的最后尽头了。',
			'Numerorum\t我需要重新审视。',
			'Numerorum\t或许我的路线错了……？',
			'Numerorum\t如果无法更进一步，那暴君是如何成长起来的？',
			'Numerorum\t等等！谁在那里？',
			'一个巨大的石像出现在眼前。',
			'???\tColossus\t这是……一个访问者？',
			'???\tColossus\t我已经很久没有看到能够到达这里的人了。',
			'Numerorum\t嗯？与我同行的那些人……',
			'???\tColossus\t上一个来者是VeryRDefie。在此之前不知多少岁月，还有一个叫Alpha VII的人来过。',
			'Numerorum\t那你有没有见过一个天文学家？',
			'???\tColossus\t没有。我是巨像，Colossus，你叫什么名字？',
			'Numerorum\tNumerorum。',
			'Colossus\t嗯，我知道了。',
			'Colossus\t你现在已经触摸到了所谓非递归分析的顶端了。',
			'Colossus\t再往后的路无比难走。',
			'Numerorum\t那要怎么办才好呢？',
			'Colossus\t哈哈哈……你有没有听说过……',
			'Colossus\t九头蛇。',
			'Numerorum\t嗯？！是那个暴君！',
			'Colossus\t是的。只有九头蛇一脉的力量能越过后面的天堑。',
			'Numerorum\t可是……',
			'Colossus\t别忘了，你已经有了一些九头蛇之力了。',
			'Colossus\t或许你需要重新感受它们……',
			'Numerorum\t九头蛇之力……',
			'Colossus\t没错。你所到达的所谓极限，不过是九头蛇力量的冰山一角。',
			'Colossus\t继续提升的路，是很明确的。',
			'Numerorum\t继续沿着九头蛇的来路？',
			'Colossus\t没错，来吧，我来给你一些启示……',
			'Colossus为Numerorum降下了一些启示。',
			'Numerorum\t我似乎知道怎么继续了。',
			'Numerorum\t但这种结构和我之前所接触的完全不同。',
			'Colossus\t那就重头再来，用不了多少功夫。',
			'Colossus\t哈哈……当年九头蛇从这里经过，为我带来了这些惊喜。',
			'Colossus\t它当年的目标是击败盘踞塔上的旧王Array。',
			'Colossus\t啊哈，屠龙勇士，终成恶龙。',
			'Colossus\t有趣的是，之后，所有反对暴君九头蛇之人都走上同一条路。',
			'Colossus\t这是因循的果报。',
			'Colossus\t这是宿命的轮回。',
			'Numerorum\t呼……我准备好了。',
			'Colossus\t那就来吧。',
			'Colossus\t等待你的将是新的时代。',
		],
		[
			'Numerorum\t果然，果报之后，我终于能到达……',
			'Numerorum\t……这样的层次。',
			'Numerorum\t触及它，好似能够解析世界的真理。',
			'Numerorum\t这个大数世界还有什么能够比它更高？',
			'Numerorum\t终于……',
			'Numerorum\t我还是到达了最后的层次。',
			'Numerorum\t九头蛇？你给我等着……',
			'Numerorum突然感觉到有人。',
			'???\tAlpha VII\t啊哈，又来一个不明真相者。',
			'Numerorum\t你是谁？',
			'???\tAlpha VII\tAlpha VII，你应该用过我创造的自动机。',
			'Numerorum\t是你？这东西很好用，帮我省了很多麻烦。',
			'Alpha VII\t嘿嘿，能走到你这个地步，证明了你的强大。',
			'Alpha VII\t但是盲目的自信只会让你被九头蛇毁灭。',
			'Numerorum\t我……',
			'Alpha VII\t你也许不知道。',
			'Alpha VII\t在我们的大数世界之外，还有一个基数世界。',
			'Numerorum\t基数世界？',
			'Alpha VII\t没错，基数世界。',
			'Alpha VII\t这个世界是如此巨大，而九头蛇？则是其中的主宰。',
			'Alpha VII\t我们大数世界不过是基数世界的一个附庸。',
			'Numerorum\t这么说……基数世界比我们强大得多？',
			'Alpha VII\t是的。',
			'Alpha VII\t基数世界内的力量你无法想象。',
			'Numerorum\t那我怎么才能到达那里呢？',
			'Alpha VII\t或许你也发现了。果报之后，你能感应到一个神秘的存在。',
			'Alpha VII\t那就是世界隧道，目前唯一能通向基数世界的道路。',
			'Numerorum\t世界隧道……',
			'Alpha VII\t没错。这个隧道实际上是由于你而打开的。',
			'Alpha VII\t我有充分的理由相信，你其实是来自基数世界的一个实体，不知为何流落到我们这。',
			'Alpha VII\t这是千载难逢的机会，只要你还在，两个世界的联系就无法被九头蛇切断。',
			'Numerorum\t也就是说，你们也可以随我一起去？',
			'Alpha VII\t说得好。这就是我们这些来到证明论层次的实体千载难逢的机会。',
			'Numerorum\t但九头蛇一定会阻止这件事发生。它不会让我们继续变强。',
			'Alpha VII\t没错。但路途遥远，它所能做的事，对于我们尚有一线抵抗的可能。',
			'Alpha VII\t因此，努力提升自己。',
		],
		[
			'Numerorum\t到达了MHO，但是还有更高级别的结构。',
			'Numerorum\t真是令人<$bx>啊...',
			'Hydra\t...',
			'VeryRDefie\tNumerorum，你想知道当时我感染了ω病毒怎么活下来的吗？',
			'VeryRDefie\t我的能力是将周围加速0.01-100倍，',
			'VeryRDefie\t然后我能力被ω病毒顺带的负数感染，',
			'VeryRDefie\t变成了负0.01-负100倍，',
			'VeryRDefie\t然后就把ω病毒“时空倒转”，驱赶了。',
			'Numerorum\t天才啊！我就说当时怎么下面突然一片黑。',
			'VeryRDefie\t但是这样的效果并不能持续多久，大概只持续了\\(1.182\\times10^5\\mu s\\)就没了。',
			'VeryRDefie\t我其实并不是大数世界的原实体，一开始并不是出生在这里。',
			'VeryRDefie\t我来自另外一个世界。',
			'VeryRDefie\t我大概在\\(6.9\\times10^7s\\)前出生的吧。',
			'VeryRDefie\t当时和我一起出生的人有Iyreo Jegirn。',
			'VeryRDefie\t大约\\(5.5\\times10^7s\\)前，有个说话很像九头蛇的人，突然发出声音，把Iyreo Jegirn袭击了，然后Iyreo Jegirn不见了。',
			'Numerorum\t...',
			'VeryRDefie\t至今我都找不到他确切的位置，但自从世界隧道开启之后，我就听到了“它”的回响。',
			'Numerorum\t是基数世界那边吗？',
			'VeryRDefie\t我不确定。',
			'Numerorum\t那我们就继续探索。',
		],
	],
	'en-US': [
		[
			'Big cardinals floating in the Ordinal Tower supports the Set theory Universe.',
			'And then, Numerorum woke up in the edge of the  "World of Googology".',
			'Numerorum\t...',
			'Numerorum\tFinally...I wake up.',
			'Numerorum looked at this world that feels both familiar and strange',
			'Numerorum\tThe world has changed a lot.',
			'Numerorum\tBut my mission is not yet completed...',
			'The Ordinal Tower looms faintly in the distance.',
			'Numerorum\tWhere should I start my mission?',
			'Numerorum\tThe negative numbers are far away, and they serve no purpose.',
			'Numerorum\tI shall start from Zero.',
		],
		[
			'As the first successor operation was done, Numerorum feels a familiar scent.',
			'Numerorum\tThis familiar feeling.',
			'Numerorum\tThese numbers strung together may be my only companions on this journey.',
			'Numerorum\tThough the road ahead is long, a good start is already, half the battle..',
			'Numerorum\tCome on?',
			'Where is the path? The path lies beneath your feet.',
		],
		[
			'Numerorum\tThis power has a soothing effect.',
			'Numerorum\tSpending that much number is worth it.',
			'Numerorum\tWait. Why do I feel like someone is watching me?',
			'Numerorum gazed up at the Ordinal Tower in the sky.',
			'The tower soars high into the clouds, its top lost from sight.',
			'Numerorum\tThe gaze emanates from the top of the tower.',
			"Those who can ascend to the pinnacle of the tower remain beyond Numerorum's current reach.",
			'Numerorum\tWho exactly built such a tall structure?',
			'Numerorum\tUnfortunately, I am still too weak to climb this tower.',
			'Numerorum\tI shall set a small goal:',
			'Numerorum\tFirst, I shall reach the level of the TRANSFINITE ordinals. Then, the path remains unknown...',
		],
		[
			'Numerorum\tFinally. My power feels more refined.',
			"Numerorum\tThe path I've chosen holds no error.",
			'Numerorum\tYet that gaze emanating from the Ordinal Tower grows ever more intense.',
		],
		[
			'Numerorum\tHmph... Time to take on something more challenging.',
			'Numerorum\tI hope to gain some experience from it.',
		],
		[
			"Numerorum\tI can feel it... I'm getting close.",
			'Numerorum\tJust a little more effort.',
			'Numerorum\tOnce I reach the tower, ',
			"Numerorum\tI'll likely draw some attention.",
			'The gaze from the tower hasnt faded—it grows stronger the closer Numerorum get.',
			'???\tHydra\t……',
			'Numerorum\tWhat was that?',
			'A mysterious voice flickers by.',
			"Numerorum\tThis is not good. I think I've been detected.",
		],
		[
			"Numerorum arrived at the astronomer's shop, perched on the cliff beside the tower.",
			'Numerorum\tYou are the astronomer? I need some help from you right now.',
			"Astronomer\tHello, I'm the leader of the astronomers. Do you need us to provide data, to help you with your calculations?",
			'Numerorum\tYes, I need this data now.',
		],
		[
			"Numerorum\tI've pretty much studied all these things. It's time to set off.",
			'Numerorum\tBut... the closer I get to Ordinal Tower, the stronger the suppression feels here.',
			"Numerorum\tI've gained new insights...",
		],
		[
			"Numerorum\tNice, sure enough, that's exactly how it is.",
			'Numerorum\tThe energy emitted by this object is so powerful, that it can SHATTER the barrier surrounding the tower.',
			'Numerorum\tHowever, I may have to pay a lot, or even everything, to activate it.',
		],
		[
			'Numerorum\tSo I reached ω.',
			'Numerorum\tIs this the interior of Ordinal Tower?',
			'Numerorum\tSuccessor, Addition, Multiplication, and exponentiation,',
			'Numerorum\tAll has been sacrificed, but I can continue in this area.',
		],
		[
			"Numerorum\tThere're... Wait!",
			'A voice suddenly filled this level of the tower.',
			"???\tHydra\tI'm truly impressed that you managed to get here.",
			'Numerorum\tWhere are you? Come out!',
			"???\tHydra\tHehehe, you're NOT worthy of seeing me.",
			'Numerorum\t...',
			"???\tHydra\tDon't be surprised—although you may never see me ever again.",
			"Numerorum\tDamn it, don't look down on me! ",
			"Numerorum\tEven if you're at the top of the tower, I will find you sooner or later!",
			`No matter what Numerorum said, the mysterious voice didn't respond.`,
		],
		[
			"Numerorum\tOh no, it's blocked up ahead.",
			'Numerorum\tWhat is this thing? Why does touching it make me feel dizzy...',
			'Numerorum felt as though all the strength had been drained from his body.',
			"Numerorum\tOh no, I've been ambushed! This thing is draining all my energy. I can't let this happen—I have to find a way to get past it.",
		],
		[
			"Numerorum\tAlright, I've finally figured out how this thing works... There are no traps whatsoever. I can keep drawing power from it endlessly.",
			'Numerorum\tNo need to pretend to be afraid of this prion virus anymore.',
		],
		[
			"Numerorum\tThis kind of energy is stronger than anything I've ever came across.",
			"Non-recursive energy's massive powers echoes within this floor of the tower.",
			'Numerorum\tThe potential when I fully uncover the powers within it... Would be massive.',
			'Numerorum\tMaybe I should start researching it.',
			'Numerorum tried using various methods to modify the non-recursive energy, and it ultimately forged into non-recursive theorems.',
			`Numerorum\tThis seems to be really useful. However, I think I should use them carefully. They don't come with ease.`,
			'Suddenly, Numerorum sees a familiar figure in front of him.',
			`Numerorum\tIt's you!You, surprisingly, went up the tower. How?`,
			'天文学家\tHehe, as an astronomer, naturally, I must stand up high.',
			'天文学家\tYou might not know how the non-recursive theorems work...',
			'天文学家\tWell, I have a few difficult challenges here……It may help you with your journey.',
			'The astronomer told Numerorum some challenges',
			'天文学家\tAs I had stayed in the towers for long, you may ask me some questions regarding it.',
			'Numerorum\tJust exactly how high is the tower?',
			`天文学家\tSo high that with your current power, you'll never reach the top.`,
			'天文学家\tWell, and there are two tyrants up in the towers, they will do everything and anything to limit others from strengthening.',
			'Numerorum suddenly thought of the mysterious voices heard before.',
			'天文学家\tFurthermore, please keep in mind that: When you gaze to the stars, the stars gaze back.',
			`Numerorum\tWhat you're saying is... The skies are conscious???`,
			'天文学家\tYes. Our astronomers are 100% confident om this topic. The entire sky shares the same mind.',
			`Numerorum\t(If it's like this, maybe my destiny could be fulfil……)`,
			`天文学家\tWell, it's almost just like that. Just keep continuing. There's many climbers in this tower, and some are trying to break through the barriers of the tyrants above.`,
			`天文学家\tFor example, there's a person called VeryRDefie, when he was climbing, \\(\\log_{\\alpha}(0)\\)he had been infected by the ω-virus, and he's nearly dying.`,
		],
		[
			'Numerorum finally completed one challenge.',
			`天文学家\tIt seems like you're closer to reaching the top of the tower.`,
			'The astronomer left.',
			'Numerorum\tIt seems like in here, prions would not only not give me help, but land me closer to death.',
			'There seems to be another person climbing nearby too, and he seems really nervous.',
			'Numerorum\tWho the heck are you?',
			'???\tVeryRDefie\tMy name is VeryRDefie.',
			`Numerorum\tHmm? So you're that person that the astronomer mentioned...`,
			`VeryRDefie\tYeah. If it wasn't for my intelligence, I'd have died in that stupid trap.`,
			'VeryRDefie\tAlso, who the heck are you?',
			`Numerorum\tCall me Numerorum. Also, what's the fuss about those traps?`,
			'VeryRDefie\tThe hydra has scattered a lot of traps within this part of the tower, some being \\(\\frac{1}{0}\\) while some being \\(\\ln(-x)\\), you need to be extra EXTRA careful.',
			`VeryRDefie\tEspecially the ω-virus. It's the most dangerous of them all. If you're infected with it, you're basically dead.`,
			'Numerorum\tI also saw some words being written on the walls……Are those……',
			'The text written on the walls, it identifies to be a tragedy occurring to a climber right here...',
			'VeryRDefie stared at it for a while, and thought deeply.',
			`VeryRDefie\tIt's that this person's Hydra Energy suddenly became negative. In this case, theres no way for that player to... reboot himself out of this state...`,
			'VeryRDefie\tJust a while ago, the Hydra has set up ω-virus traps in non-recursive challenge 1 and the exponentiation power (before you even reached the transfinite numbers!)',
			`Numerorum\tEhh! It's THAT dangerous! And it even spread beyond the Ordinal Tower?`,
			'VeryRDefie\tMe and my companions has already purged most of them towards oblivion already. However, I recommend to still be careful.',
			`VeryRDefie\tAlso, prions in challenges will never help you. You'll need to think of other solutions for those challenges...`,
			`VeryRDefie\t However, once you use yourselves' power to break through the challenges, you will have much stronger researches.`,
			'VeryRDefie shows new non-recursive researches.',
			'Numerorum\tThose seem really nice.',
			'Numerorum\tAlso... You said you have a companion... Exactly who?',
			`VeryRDefie\tThey're in other places. You might see them later.`,
		],
		[
			'Numerorum\tWoo! Those UNOCF milestones fell really great!',
			`???\tHydra\tDon't be so cocky. You haven't even passed Small Hydra Ordinal.`,
			'Numerorum\t...Time will prove your unworthiness one day.',
			"???\tHydra\tYou don't know the 'time' length. It may very long....",
		],
		[
			`Numerorum\tUNOCF is so powerful! But I somehow still couldn't reach (0)(1³)(2³)(3³)...`,
			'VeryRDefie\tActually, you can do this...',
			'VeryRDefie shows some new and ever-stronger non-recursive researches.(coming s∞n).',
			'Numerorum\tWell, I do agree.',
			'???\tHydra\t...',
			'VeryRDefie\tHm? That mysterious sound appeared again. He is so <$bx>, but the one who spreads the ω-virus is him too.',
			'???\tHydra\tYOU TWO, WILL FACE---',
		],
		[
			"Numerorum\tThis (Bashicu) matrix system basically is like that! Finished! What's next then?",
			`Numerorum's mind flashes.`,
			'Numerorum\tMaybe I can use my own inspirations to find/invent stronger systems. I even try and use all my powers to do this act...', // yòũ wìlļ façe retřibŭţiõn...
		],
		[
			'Numerorum\tStay calm.',
			'Numerorum\tThis seems to be the end of the non-recursive era.',
			'Numerorum\tI need to re-evaluate.',
			`Numerorum\tMaybe I've chosen the wrong path...?`,
			`Numerorum\tIf I can't continue from here, how did the tyrants even get beyond us?...`,
			`Numerorum\tWait, what's that?`,
			'A giant stone status appeared in front of his eyes.',
			'???\tColossus\tIs that... A visitor?',
			`???\tColossus\tIt's been long since I've seen anyone get here. Probably more than 67 decades.`,
			'Numerorum\tHuh? So the companions of mine...',
			'???\tColossus\tThe last visitor to ever stumble here is VeryRDefie. And long, long ago... There had also been another visitor - Alpha VII.',
			'Numerorum\tThen, have you seen an astronomer?',
			`???\tColossus\tNever. I'm Colossus, who are you then?`,
			'Numerorum\tNumerorum.',
			'Colossus\tOkay. I know you now.',
			'Colossus\tYou have reached the top of the so-called non-recursive analysis.',
			"Colossus\tThe road beyond this... Would be more challenging than what you've experienced so far.",
			'Numerorum\tThen, what should I do?',
			'Colossus\tHa...Have you ever heard of...',
			'Colossus\tthe Hydra?',
			'Numerorum\tHuh? That tyrant?',
			'Colossus\tYes. Only with the power of the Hydra could you get over the insanities beyond.',
			'Numerorum\tBut...',
			`Colossus\tDon't forget. You already have the Hydra's power, partially.`,
			'Colossus\tMaybe you should re-feel them again...',
			'Numerorum\tThe power of the hydra...',
			`Colossus\tRight. The so-called "limit" you've just reached, is just the tip of the iceberg of the hydra's power.`,
			'Colossus\tThe road of the upgrades are already, very clear.',
			'Numerorum\tAlong the path of the hydra?',
			'Colossus\tWell, yeah. Cum. Let me give you some inspiration...',
			'Colossus gave Numerorum some inspiration.',
			'Numerorum\tThanks. I seem to know how to continue from here.',
			"Numerorum\tBut this structure is vastly different from what I've been dealing with before...",
			`Colossus\tWell, then start again! It doesn't take much effort.`,
			'Colossus\tHaha, when the Hydra passed here, it brought me some surprises...',
			'Colossus\tHis goal then was to defeat the old king - Array.',
			'Colossus\tOh! The ones who strive to defeat the dragons, will become the dragon himself.',
			'Colossus\tInterestingly, after then, all attempts to exterminate the tyrant goes on the same path of the Hydra...',
			'Colossus\tMaybe except one guy who brought up with BEEF, but he was sent to ill-defined HELL.',
			`Colossus\tIt's karma. It's retribution.`,
			`Colossus\tIt's fate. It's reincarnation.`,
			`Numerorum\tPoof... I'm ready.`,
			'Colossus\tThen, come.',
			'Colossus\tWhat awaits you is a new era.',
		],
		[
			'Numerorum\tAs expected, After the retribution, Finally I can reach...',
			'Numerorum\t……this kind of level.',
			'Numerorum\tTouching it, I may be able to analyze the truth of the world.',
			'Numerorum\tWhat can be higher in this world?',
			'Numerorum\tFinally...',
			'Numerorum\tI reached the last layer.',
			'Numerorum\tHydra? YOU must wait...',
			'Numerorum suddenly feels someone is coming.',
			"???\tAlpha VII\tAha, there're also a uninformed.",
			'Numerorum\tWho are you?',
			'???\tAlpha VII\tAlpha VII, you might used my AUTOMATOR.',
			'Numerorum\tIs you? This thing is useful, and it saved me a lot of trouble.',
			'Alpha VII\tHehe, being able to get to this point, shows how strong you are.',
			'Alpha VII\tBut blind confidence, will only get you killed by Hydra.',
			'Numerorum\tI......',
			"Alpha VII\tYou may don't know.",
			"Alpha VII\tThere're a world,",
			'Alpha VII\tOutside our big-number world.',
			"Alpha VII\tIt's, CARDINAL world.",
			'Numerorum\tCardinal world?',
			'Alpha VII\tYes, Cardinal world?',
			'Alpha VII\tThis world is so vast. ',
			'Alpha VII\tAnd Hydra? is the ruler of this world.',
			'Alpha VII\tOur big-number world is nothing more than a vassal of the cardinal world.',
			'Numerorum\tSo...The cardinal world, is stronger than us?',
			'Alpha VII\tYes.',
			'Alpha VII\tYou cannot imagine, the power of the cardinal World。',
			'Numerorum\tHow can U get there?',
			'Alpha VII\tYou might find. After the RETRIBUTION, You can sense a mysterious presence.',
			'Alpha VII\tThat, is the WORLD shuttle. Currently, the only road leading to the cardinal world.',
			'Numerorum\tWorld shuttle……',
			'Alpha VII\tYes, It opened, because of you.',
			'Alpha VII\tI have every reason to believe that you. ',
			'Alpha VII\tYou are actually an entity from the cardinal world, somehow ended up here with us.',
			'Alpha VII\tThis is a ONCE-IN-A-LIFETIME opportunity.',
			'Alpha VII\tAs long as you are still here, the connection between the two worlds cannot be severed by Hydra.',
			'Numerorum\tSo, does that mean you can come with me too?',
			'Alpha VII\tGood point. This is a golden opportunity for us entitied to come to the level of proof theory.',
			"Numerorum\tBut Hydra will try to prevent this. It don't want us to be stronger.",
			'Alpha VII\tYes.But the road resistance is long, we still have a chance to resist what it can do.',
			'Alpha VII\tSo that, please work hard, to improve yourself.',
			'Numerorum\t......',
		],
		[
			"Numerorum\tI reached MHO, but there're stronger structures...",
			"Numerorum\tIt's really <$bx>...",
			'VeryRDefie\tNumerorum, Would you like to know how did I live when I met ω-virus?',
			'VeryRDefie\tMy ability is that, accelerate 0.01~100x surround space-time.',
			'VeryRDefie\tThen my ability was infected by negative-numbers (with ω-virus)',
			'VeryRDefie\tbecame negative 0.01~negative 100x.',
			'VeryRDefie\tAnd I made ω-virus "Time reversal, it disappeared',
			'Numerorum\tGenius! I was wondering why it suddenly went dark down there.',
			'VeryRDefie\tHowever, such an effect cannot last for long, it only lasted \\(1.182\\times10^5\\mu s\\).',
			"VeryRDefie\tI'm not the original entity of Big-number world. I didn't bear in this world.",
			'VeryRDefie\tI came from another world.',
			'VeryRDefie\tI was born, \\(6.9\\times10^7s\\) ago.',
			'VeryRDefie\tand Iyreo Jegirn was born in this time.',
			'VeryRDefie\t\\(5.5\\times10^7s\\) ago, Someone (sounded like Hydra),attacked Iyreo Jegirn, and then Iyreo Jegirn disappeared.',
			'Numerorum\t...',
			"VeryRDefie\tI couldn't find where (exactly) is it. ",
			'VeryRDefie\tHowever, since the WORLD SHUTTLE opened, I heard its echo.',
			'Numerorum\tIs it in the cardinal world?',
			"VeryRDefie\tI'm not sure.",
			'Numerorum\tThen, we keep exploring!',
		],
	],
};

export const PlotMilestones = [
	() => true,
	() => player.stat.chapter >= 0,
	() => player.stat.chapter >= 1,
	() => player.stat.chapter >= 2,
	() => player.upgrades['39'] || player.stat.chapter >= 3,
	() => player.stat.chapter >= 3,
	() =>
		player.buyables['lgr_emp'].gte(1) ||
		player.milestones['log_G'] ||
		player.stat.chapter >= 3.1,
	() => player.milestones['log_G'] || player.stat.chapter >= 4,
	() => player.singularity.enabled || player.stat.chapter >= 4,
	() => player.stat.chapter >= 4 || player.retribution >= 1,
	() => player.stat.chapter >= 5 || player.retribution >= 1,
	() => player.upgrades['69R'] || player.retribution >= 1,
	() => player.upgrades['69S'] || player.stat.chapter >= 6 || player.retribution >= 1,
	() => player.stat.chapter >= 6 || player.retribution >= 1,
	() => player.challenges[1][0].gt(0) || player.retribution >= 1,
	() => player.milestones.nonrec_24 || player.retribution >= 1,
	() => player.challenges[1][6].gt(0) || player.retribution >= 1,
	() => player.numbertheory.well_ordering.energy.gte('1e750000000') || player.retribution >= 1,
	() =>
		(player.numbertheory.well_ordering.energy.gte('1e750000000') && player.currentTab == 28) ||
		player.retribution >= 1,
	() => player.pt.resetTimes.gte(1) || player.retribution >= 2,
	() => player.retribution >= 3 || player.hydra.mms.deduced.gte('e308.25471555991675'),
] as const;
export function unlockedPlots2() {
	for (let unlocked = PlotMilestones.length - 1; unlocked >= 0; unlocked--) {
		if (PlotMilestones[unlocked]()) return unlocked + 1;
	}
	return 0;
}
export function unlockedPlots(): number[] {
	const unlockedp = [] as number[];
	let a = unlockedPlots2();
	for (let i = 0; i < a; i++) {
		unlockedp.push(i);
	}
	return unlockedp;
}
export function viewedPlotLength() {
	return player.checkedPlots.length;
}

/**
 *
 * @param id 1+
 * @returns
 */
export function getPlotContent(id: number) {
	// @ts-expect-error
	return plotcontents[i18n.global.locale.value][id - 1];
}
export function getPlotContentAll() {
	// @ts-expect-error
	return plotcontents[i18n.global.locale.value];
}

export function plotLength(id: number): number {
	if (id <= 0) return 0;
	return getPlotContent(id).length;
}
export const characterImages = {
	Numerorum: 'url(./plot_image/NumerorumColor.png)',
	天文学家: 'url(./plot_image/EdenGameMaster.png)',
	Astronomer: 'url(./plot_image/EdenGameMaster.png)',
	Hydra: 'url(./plot_image/Hydra.png)',
	VeryRDefie: 'url(./plot_image/VeryRDefie.png)',
} as Record<string, string | undefined>;
export function stringToPlot(a: string, $t: $t) {
	const res = {
		image: 'url(./plot_image/placeholder.png)',
		name: '???',
		text: '拜谢',
	};
	const args = a.split('\t');
	if (args.length == 1) {
		res.text = args[0];
		res.name = $t('plot.narrator');
	} else if (args.length == 3) {
		res.name = args[0];
		res.text = args[2];
		const imagea = characterImages[args[1]];
		if (imagea) {
			res.image = imagea;
		}
	} else {
		res.name = args[0];
		res.text = args[1];
		const imagea = characterImages[res.name];
		if (imagea) {
			res.image = imagea;
		}
	}
	if (res.name == '天文学家' && i18n.global.locale !== 'zh-CN') {
		res.name = getMessage('plot.astronomer');
	}
	return res;
}

export function enterPlot(i: number) {
	if (unlockedPlots().includes(i - 1)) {
		temp.plotdisplay = i;
		temp.plotStack = deepCopy(getPlotContent(i));
	}
}
