name: Type Check, Build & Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [develop]
  push:
    branches: [develop]

jobs:
  type-check-and-build:
    name: Type Check & Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Project
        run: npm run build
        
  deploy-to-pages:
    name: Deploy to GitHub Pages
    needs: type-check-and-build
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        if: success()